/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mypack;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.Scanner;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import org.json.*;
/**
 *
 * @author ABHIJITH H
 */
public class esphome extends javax.swing.JFrame {

    /**
     * Creates new form esphome
     */
    public esphome() {
        initComponents();
          scantb.getTableHeader().setForeground(new java.awt.Color(25,29,35));
          
        scantb.getTableHeader().setFont(new Font("Courier New",Font.BOLD,18));
        scantbscroll.getViewport().setBackground(new java.awt.Color(38,38,38));
         String[] quotes = {
                "<html><div style='width:105px; text-align:center;'> ⚠️ Unauthorized attacks are illegal.</html></div>",
                "<html><div style='width:105px; text-align:center;'>🔍 Listening is learning — scan wisely.</html></div>",
                "<html><div style='width:105px; text-align:center; '>💻 AIRHEX is a tool, not a weapon.</html></div>",
                 "<html><div style='width:105px; text-align:center;'>⚡ Precision matters more than power.</html></div>",
                "<html><div style='width:105px; text-align:center;'>🌐 You are connected. But are you aware?</html></div>"
            };

            Timer quoteTimer = new Timer(4000, new ActionListener() {
            int idx = 0;
            public void actionPerformed(ActionEvent e) {
                qtlabel.setText(quotes[idx]);
                 idx = (idx + 1) % quotes.length;
            }
            });
            quoteTimer.setInitialDelay(0);
            quoteTimer.start();
//       scantb.getColumnModel().getColumn(1).setPreferredWidth(70); 
//       scantb.getColumnModel().getColumn(2).setPreferredWidth(10); 
//       scantb.getColumnModel().getColumn(3).setPreferredWidth(20);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        qtlabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        scantbscroll = new javax.swing.JScrollPane();
        scantb = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        scanindicator = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(996, 468));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(17, 17, 17));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 430));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("ROG Fonts", 1, 45)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("HEX");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 140, 130, 40);

        jLabel5.setFont(new java.awt.Font("ROG Fonts", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("Air");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 100, 107, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhij\\Downloads\\hack (2).png")); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 30, 70, 80);

        qtlabel.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        qtlabel.setForeground(new java.awt.Color(255, 255, 255));
        qtlabel.setText("<html><div style='width:100px; text-align:center;'>github.com/A4BHI</div></html>");
        jPanel1.add(qtlabel);
        qtlabel.setBounds(0, 170, 150, 100);

        jLabel8.setBackground(new java.awt.Color(153, 255, 255));
        jLabel8.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("<html><div style='width:100px; text-align:center;'>🔒 Stay aware.<br>Wi-Fi is your battlefield.<br>Use tools with ethics.</div></html>");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 320, 180, 80);

        jPanel5.setBackground(new java.awt.Color(17, 17, 17));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 225), 1, true));

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("<html><div style='width:100px;'>github.com/A4BHI</div></html>");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(10, 260, 120, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -2, 140, 440);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(30, 30, 30));
        jPanel4.setLayout(null);

        scantb.setBackground(new java.awt.Color(25, 29, 35));
        scantb.setFont(new java.awt.Font("Courier New", 1, 15)); // NOI18N
        scantb.setForeground(new java.awt.Color(255, 255, 255));
        scantb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SSID", "BSSID", "RSSI", "ENC", "VENDOR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scantb.setGridColor(new java.awt.Color(0, 255, 225));
        scantb.setRowHeight(30);
        scantb.setSelectionBackground(new java.awt.Color(0, 255, 225));
        scantb.setSelectionForeground(new java.awt.Color(51, 51, 51));
        scantb.setShowGrid(true);
        scantb.getTableHeader().setReorderingAllowed(false);
        scantbscroll.setViewportView(scantb);
        if (scantb.getColumnModel().getColumnCount() > 0) {
            scantb.getColumnModel().getColumn(0).setPreferredWidth(90);
            scantb.getColumnModel().getColumn(1).setResizable(false);
            scantb.getColumnModel().getColumn(1).setPreferredWidth(65);
            scantb.getColumnModel().getColumn(2).setMinWidth(70);
            scantb.getColumnModel().getColumn(2).setMaxWidth(100);
            scantb.getColumnModel().getColumn(3).setMinWidth(100);
            scantb.getColumnModel().getColumn(3).setPreferredWidth(30);
            scantb.getColumnModel().getColumn(3).setMaxWidth(100);
            scantb.getColumnModel().getColumn(4).setResizable(false);
            scantb.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        jPanel4.add(scantbscroll);
        scantbscroll.setBounds(-1, 149, 840, 300);

        jPanel6.setBackground(new java.awt.Color(42, 42, 42));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 225), 1, true));
        jPanel6.setLayout(null);

        jTextField1.setBackground(new java.awt.Color(28, 28, 28));
        jTextField1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jTextField1);
        jTextField1.setBounds(120, 10, 210, 30);

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MAC Address:");
        jPanel6.add(jLabel3);
        jLabel3.setBounds(10, 10, 110, 30);

        jButton4.setBackground(new java.awt.Color(0, 255, 153));
        jButton4.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jButton4.setText("Deauth");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 225)));
        jPanel6.add(jButton4);
        jButton4.setBounds(340, 10, 110, 30);

        jPanel4.add(jPanel6);
        jPanel6.setBounds(380, 90, 460, 50);

        jPanel7.setBackground(new java.awt.Color(42, 42, 42));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 225), 1, true));
        jPanel7.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("AIRHEX");
        jPanel7.add(jLabel1);
        jLabel1.setBounds(270, -10, 170, 80);

        jLabel2.setFont(new java.awt.Font("Poor Richard", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("-Explore.   Disrupt.   Control.   - AirHex on ESP32 ");
        jPanel7.add(jLabel2);
        jLabel2.setBounds(440, 30, 290, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhij\\Downloads\\hack (4).png")); // NOI18N
        jPanel7.add(jLabel6);
        jLabel6.setBounds(240, 0, 50, 60);

        jPanel4.add(jPanel7);
        jPanel7.setBounds(0, 30, 840, 50);

        scanindicator.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        scanindicator.setForeground(new java.awt.Color(0, 255, 204));
        scanindicator.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhij\\Downloads\\hack (5).png")); // NOI18N
        jPanel4.add(scanindicator);
        scanindicator.setBounds(0, 80, 210, 30);

        jButton5.setBackground(new java.awt.Color(0, 255, 153));
        jButton5.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jButton5.setText("Stop Spam");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 225)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(260, 110, 110, 30);

        jButton3.setBackground(new java.awt.Color(0, 255, 153));
        jButton3.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jButton3.setText("Scan WiFi");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 225)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(0, 110, 90, 30);

        jButton6.setBackground(new java.awt.Color(0, 255, 153));
        jButton6.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jButton6.setText("Beacon Spamming");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 225)));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(100, 110, 150, 30);

        jTabbedPane1.addTab("tab1", jPanel4);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -50, 860, 510));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(100, 0, 900, 490);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public String getvendor(String bssid){
     String macapi="https://api.macvendors.com/"+bssid;
     try{
     URL url=new URL(macapi);
     HttpURLConnection con=(HttpURLConnection) url.openConnection();
     con.setRequestMethod("GET");
     con.connect();
     
     Scanner sc=new Scanner(con.getInputStream());
     String vendor=sc.nextLine();
     sc.close();
     return vendor;
     
     }catch(Exception e){System.out.println(e);}
      return "Unknown Vendor";
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        new Thread(()->{
           
                 try{
           
           SwingUtilities.invokeLater(() -> scanindicator.setText("Starting.."));
           Thread.sleep(3000);
           URL url=new URL("http://192.168.59.15/scan");
        
           HttpURLConnection con=(HttpURLConnection) url.openConnection();
           con.setRequestMethod("GET");
           
           SwingUtilities.invokeLater(() -> scanindicator.setText("Scanning.."));
           con.connect();
           
           if(con.getResponseCode()==200){
                for(int i=1;i<=100;i++){
                    scanindicator.setText("Scanning "+i+"%");
                    Thread.sleep(10);
               }
                Thread.sleep(10);
               Scanner sc=new Scanner(con.getInputStream());
               StringBuilder response=new StringBuilder();
               while(sc.hasNextLine()){
                   response.append(sc.nextLine());
               }
               sc.close();
               System.out.println(response);
              
              
               JSONArray jsarr= new JSONArray(response.toString());
                DefaultTableModel tb=(DefaultTableModel)scantb.getModel();
                SwingUtilities.invokeLater(() -> tb.setRowCount(0));
               for(int i=0;i<jsarr.length();i++){
                  JSONObject obj = jsarr.getJSONObject(i);
                   final String ssid = obj.getString("ssid");
                   final String BSSID = obj.getString("mac");
                   final int RSSI = obj.getInt("rssi");
                   final String encryption=obj.getString("enc");
                   Thread.sleep(1000);
                   final String vendor=getvendor(BSSID);
                   
                     SwingUtilities.invokeLater(() -> tb.addRow(new Object[]{ssid,BSSID,RSSI,encryption,vendor}));
               
               }
                Thread.sleep(1000);
                SwingUtilities.invokeLater(() -> scanindicator.setText("Scanning Completed."));
                
           }
       
       
       }catch(Exception e){System.out.println(e);}
        
        
        
        }).start();
       
   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         new Thread(()->{
            try{
                URL url=new URL("http://192.168.59.15/stop");
                HttpURLConnection con=(HttpURLConnection)url.openConnection();
                con.setRequestMethod("GET");
                con.connect();
                System.out.print(con.getResponseCode());
                 SwingUtilities.invokeLater(() -> scanindicator.setText("Spamming Stoped"));
            
            }catch(Exception e){System.out.print(e);}
        
        }).start(); 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new Thread(()->{
            try{
                URL url=new URL("http://192.168.59.15/start");
                HttpURLConnection con=(HttpURLConnection)url.openConnection();
                con.setRequestMethod("GET");
                con.connect();
                 System.out.print(con.getResponseCode());
                 SwingUtilities.invokeLater(() -> scanindicator.setText("Spamming Started"));
            
            }catch(Exception e){System.out.print(e);}
        
        }).start(); 
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(esphome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(esphome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(esphome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(esphome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new esphome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel qtlabel;
    private javax.swing.JLabel scanindicator;
    private javax.swing.JTable scantb;
    private javax.swing.JScrollPane scantbscroll;
    // End of variables declaration//GEN-END:variables
}
